# Generated by Django 3.0.8 on 2020-09-14 09:36

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200903_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='GiftOpener',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.RemoveField(
            model_name='knowledgeshare',
            name='length',
        ),
        migrations.RemoveField(
            model_name='knowledgeshare',
            name='sort_by',
        ),
        migrations.RemoveField(
            model_name='knowledgeshare',
            name='users',
        ),
        migrations.AddField(
            model_name='knowledgeshare',
            name='messages',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='KnowledgeGift',
        ),
    ]
