# Generated by Django 3.0.8 on 2020-09-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200914_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='emotion_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.EmotionProfile'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='gamer_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.GamerProfile'),
        ),
    ]
