# Generated by Django 3.0.8 on 2020-10-09 11:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200916_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionstatistic',
            name='log',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
