# Generated by Django 3.0.8 on 2020-10-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20201009_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactionstatistic',
            name='log',
        ),
    ]
