# Generated by Django 3.0.8 on 2020-10-09 13:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_interactionstatistic_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionstatistic',
            name='log',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
